name: Check and test app

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Install packages
        run: npm ci
      - name: Build page
        run: npm run build
      - name: Check page
        run: npm run check
      - name: Lint page
        run: npm run lint
